---@alias float number
---@alias int integer

---@alias ModOption {
---     type: string,
---     id: string,
---     name: string,
---     value: any,
---     tooltip: string,
---     isEnabled: boolean,
---     values: {name: string, value: any, isEnabled: boolean}[],
---     nameToIndex: {[string]: number},
---     getValue: fun(self: ModOption, index: number|nil): any,
---     setValue: fun(self: ModOption, index: number|nil, value: any),
---     setEnabled: fun(self: ModOption, bool: boolean)
--- }

---@alias ModOptions.Options {
---     data: table,
---     dict: {[string]: ModOption},
---     modOptionsID: string,
---     name: string,
---     apply: function,
---     addDescription: fun(self: ModOptions.Options, desc: string),
---     addSeparator: fun(),
---     addComboBox: fun(self: ModOptions.Options, id: string, name: string, _tooltip: string|nil),
---     addMultipleTickBox: fun(self: ModOptions.Options, id: string, name: string, _tooltip: string|nil),
---     addTickBox: fun(self: ModOptions.Options, id: string, name: string, value: boolean, _tooltip: string|nil),
---     addKeyBind: fun(self: ModOptions.Options, id: string, name: string, key: integer, _tooltip: string|nil),
---     addSlider: fun(self: ModOptions.Options, id: string, name: string, min: float, max: float, step: float, value: float, _tooltip: string|nil),
---     addColorPicker: fun(self: ModOptions.Options, id: string, name: string, r: float, g: float, b: float, a: float, _tooltip: string|nil),
---     addButton: fun(self: ModOptions.Options, id: string, _tooltip: string|nil, onclickfunc: function, target: any, arg1: any, arg2: any, arg3: any, arg4: any),
--- }
